version: '3.8'

services:
  db:
    image: postgres:16
    container_name: f3d-manager-db
    restart: always
    environment:
      POSTGRES_DB: f3d_manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: f3d-manager-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - ./.docker/servers.json:/pgadmin4/servers.json  # <- Adiciona configuração automática do servidor

volumes:
  pgdata: