spring:
  application:
    name: f3d-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/f3d_manager
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true